.TH GIT-FIND-UNCOMMITTED-REPOS "1" "February 2015" "git-uncommitted-repos" "User Commands"
.SH NAME
git-find-uncommitted-repos \- recursively list repositories with uncommited changes
.SH SYNOPSIS
.B git find-uncommitted-repos
[\fIDIR...\fR]
.SH OPTIONS
.TP
.B -h\fR|\fB--help
show this page.
.TP
.B -v\fR|\fB--verbose
print more details about what is being done.
.TP
.B -u\fR|\fB--untracked
count untracked files as 'uncommited'
.TP
.I DIR...
.br
the directories to scan, or current directory if none is specified.
.SH COPYRIGHT
Copyright \(co 2013 Rodrigo Silva (MestreLion) <linux@rodrigosilva.com>
.br
License: GPLv3 or later. See <http://www.gnu.org/licenses/gpl.html>
