.TH GIT-RESTORE-MTIME "1"
.SH NAME
git-restore-mtime \- restore mtimes to the last commit's date
.SH DESCRIPTION
usage: git\-restore\-mtime [\-h] [\-\-quiet] [\-\-verbose] [\-\-force] [\-\-merge]
.TP
[\-\-skip\-missing] [\-\-no\-directories] [\-\-test]
[\-\-work\-tree WORKDIR] [\-\-git\-dir GITDIR]
[pathspec [pathspec ...]]
.PP
Restore original modification time of files based on the date of the most
recent commit that modified them. Useful when generating release tarballs.
.SS "positional arguments:"
.TP
pathspec
only modify paths (dirs or files) matching PATHSPEC,
relative to current directory. Default is to modify
all non\-ignored, tracked files.
.SS "optional arguments:"
.TP
\fB\-h\fR, \fB\-\-help\fR
show this help message and exit
.TP
\fB\-\-quiet\fR, \fB\-q\fR
suppress informative messages and summary statistics.
.TP
\fB\-\-verbose\fR, \fB\-v\fR
print additional information for each processed file.
Overwrites \fB\-\-quiet\fR.
.TP
\fB\-\-force\fR, \fB\-f\fR
force execution on trees with uncommited changes.
.TP
\fB\-\-merge\fR, \fB\-m\fR
include merge commits. Leads to more recent mtimes and
more files per commit, thus with the same mtime (which
may or may not be what you want). Including merge
commits may lead to less commits being evaluated (all
files are found sooner), which improves performance,
sometimes substantially. But since merge commits are
usually huge, processing them may also take longer,
sometimes substantially. By default merge logs are
only used for files missing from regular commit logs.
.TP
\fB\-\-skip\-missing\fR, \fB\-s\fR
do not try to find missing files. If some files were
not found in regular commit logs, by default it retries using merge commit logs for these files (if
\fB\-\-merge\fR was not used already). This option disables
this behavior, which may slightly improve performance,
but files found only in merge commits will not be
updated.
.TP
\fB\-\-no\-directories\fR, \fB\-D\fR
do not update directory mtime for files created,
renamed or deleted in it. Note: just modifying a file
will not update its directory mtime.
.TP
\fB\-\-test\fR, \fB\-t\fR
test run: do not actually update any file
.TP
\fB\-\-work\-tree\fR WORKDIR
specify where the work tree is. Default for most
repositories is current directory.
.TP
\fB\-\-git\-dir\fR GITDIR
specify where the git repository is. Default for most
repositories <work\-tree>/.git
