.mso www.tmac
.TH GIT-STRIP-MERGE "1" "February 2015" "git-strip-merge" "User Commands"
.SH NAME
git-strip-merge \- a \fBgit-merge\fR wrapper that delete files on a "foreign"
branch before merging
.SH SYNOPSIS
.B git strip-merge
[\fIgit-merge options\fR] [\fB-M \fI<commitmsg>\fR] \fI<branch> FILE...
.SH DESCRIPTION
git-merge that delete files on "foreign" \fI<branch>\fR before merging
.PP
Useful for ignoring a folder in \fI<branch>\fR before merging it with
current branch. Works by deleting \fIFILE\fR(\fIS\fR) in a detached commit based
on <branch>, and then performing the merge of this new commit in the
current branch. Note that \fI<branch>\fR is not changed by this procedure.
Also note that <branch> may actually be any reference, like a tag,
or a remote branch, or even a commit SHA.
.PP
For more information, see
.URL http://stackoverflow.com/questions/3111515
.SH OPTIONS
.B -h\fR,\fB --help
show this page.
.TP
.B -v\fR,\fB --verbose
do not use \fB-q\fR to suppress normal output of internal steps from git
checkout, rm, commit. By default, only git merge output is shown.
.br
Errors, however, are never supressed.
.TP
.B -M \fI<message>\fR,\fB --msgcommit=\fI<message>
message for the removal commit in \fI<branch>\fR. Not to be confused
with the message of the merge commit, which is set by \fB-m\fR. Default
message is: \fU"remove files from '<branch>' before merge"\fR
.TP
.B -m \fI<message>\fR,\fB --message=\fI<message>
message for the merge commit. Since we are not merging <branch>
directly, but rather a detached commit based on it, we forge a
message similar to git's default for a branch merge. Otherwise
git would use in message the full and ugly SHA1 of our commit.
Default message is: \fU"Merge stripped branch '<branch>'"\fR
.TP
For both commit messages, the token "<branch>" is replaced for the actual \fI<branch>\fR name.
.TP
Additional options are passed unchecked to git merge.
.TP
All options must precede \fI<branch>\fR and \fIFILE\fR(s), except \fB-h\fR
and \fB--help\fR that may appear anywhere on the command line.
.TP
Example:
.IP
git strip-merge design "photoshop/*"
.SH COPYRIGHT
Copyright \(co 2013 Rodrigo Silva (MestreLion) <linux@rodrigosilva.com>
.br
License: GPLv3 or later. See <http://www.gnu.org/licenses/gpl.html>
